--------------------------------------------------------
--  File created - Sunday-October-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LEG_INSTANCE
--------------------------------------------------------

  CREATE TABLE "CS4347F18"."LEG_INSTANCE" 
   (	"FLIGHT_NUMBER" NUMBER(*,0), 
	"LEG_NUMBER" NUMBER(*,0), 
	"DATE1" DATE, 
	"NUMBER_OF_AVAIABLE_SEATS" NUMBER(*,0), 
	"AIRPLANE_ID" NUMBER(*,0), 
	"DEPARTURE_AIRPORT_CODE" NUMBER(*,0), 
	"DEPARTURE_TIME" TIMESTAMP (6), 
	"ARRIVAL_AIRPORT_CODE" NUMBER(*,0), 
	"ARRIVAL_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into CS4347F18.LEG_INSTANCE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C009977
--------------------------------------------------------

  CREATE UNIQUE INDEX "CS4347F18"."SYS_C009977" ON "CS4347F18"."LEG_INSTANCE" ("FLIGHT_NUMBER", "LEG_NUMBER", "DATE1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LEG_INSTANCE
--------------------------------------------------------

  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("FLIGHT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("LEG_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("DATE1" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("NUMBER_OF_AVAIABLE_SEATS" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("AIRPLANE_ID" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("DEPARTURE_AIRPORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("DEPARTURE_TIME" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("ARRIVAL_AIRPORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" MODIFY ("ARRIVAL_TIME" NOT NULL ENABLE);
  ALTER TABLE "CS4347F18"."LEG_INSTANCE" ADD PRIMARY KEY ("FLIGHT_NUMBER", "LEG_NUMBER", "DATE1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
