married(profPlum,msGreen).
affair(mrBody,msGreen).
affair(missScarlet,mrBody).
spouse(X,Y):-married(X,Y).
spouse(Y,X):-married(X,Y).
hatred(X,Y):-spouse(X,Z),affair(Y,Z).
rich(mrBody).
greedy(colMustard).
not(rich(colMustard)).
greed(X,Y):-not(rich(X)),rich(Y).